### ISSUE TITLE
Error doesn't throw exception for debugging

### ISSUE THREAD

**Issue by mrfleap** [ArnavChawla/RequestSoup#2]
https://github.com/ArnavChawla/RequestSoup/blob/348bd0bd3648891c5c09a51768d07e4b16d1f3dc/src/RequestSoup.py#L73

I recommend using `except Exception as err:` and throwing the error after the debug statement with `raise err`

**Comment by ArnavChawla** [comment]
I fixed this. Thank you for your feedback

**Comment by mrfleap** [comment]
You are welcome :octocat:
